# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: CavSecurityPipelineCP99@1
  displayName: 'Cavisson Full Security Flow'
  inputs:
    cavScanServiceConnection: 'cav-scan-demo'
    securityScanApiBaseUrl: 'https://sonar1.cav-test.com:4444'

    applicationType: 'dotnet'

    runStaticScan: true
    staticEngine: 'sonarqube'
    project: 'eshoponweb'
    targetPath: ''

    buildCommand: |
      dotnet restore eShopOnWeb.sln
      dotnet build eShopOnWeb.sln --configuration Release --no-restore

    dockerBuildCommand: |
      docker build -t eshoponweb:$(Build.BuildNumber) -f src/Web/Dockerfile .

    containerEngine: 'trivy'
    containerRunMode: 'standalone'
    imageName: 'eshoponweb:$(Build.BuildNumber)'
    trivyMode: 'image'
    trivyTarget: 'eshoponweb:$(Build.BuildNumber)'

    deployCommand: |
      docker rm -f eshoponweb-test || true
      docker run -d --name eshoponweb-test -p 3001:8080 -e ASPNETCORE_URLS=http://+:8080 eshoponweb:$(Build.BuildNumber)
      sleep 20
      docker ps
      curl -I http://127.0.0.1:3001 || true

    dynamicEngine: 'zap'
    dynamicRunMode: 'standalone'
    zapMode: 'baseline'
    zapTarget: 'http://127.0.0.1:3001'

    allowInsecureSSL: true